-- ============================================================
-- B2B Sales Intelligence - Schema and Star Schema Tables
-- Database: TELCO_AI_DEMO
-- Schema: B2B_SALES
-- ============================================================

CREATE SCHEMA IF NOT EXISTS TELCO_AI_DEMO.B2B_SALES
  COMMENT = 'B2B Sales Intelligence for top 50 Dutch enterprise accounts';

USE SCHEMA TELCO_AI_DEMO.B2B_SALES;

-- Dimension: Companies (50 top Dutch enterprises)
CREATE OR REPLACE TABLE DIM_COMPANY (
    COMPANY_ID INT PRIMARY KEY,
    COMPANY_NAME VARCHAR(200),
    INDUSTRY VARCHAR(100),
    SECTOR VARCHAR(100),
    HEADQUARTERS_CITY VARCHAR(100),
    EMPLOYEE_COUNT INT,
    ANNUAL_REVENUE_EUR FLOAT,
    WEBSITE VARCHAR(200),
    ACCOUNT_TIER VARCHAR(20),
    ACCOUNT_MANAGER VARCHAR(100),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
) COMMENT = 'Top 50 Dutch enterprise B2B customer accounts';

-- Dimension: Products (10 B2B telco products)
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200),
    PRODUCT_CATEGORY VARCHAR(100),
    MONTHLY_LIST_PRICE_EUR FLOAT,
    DESCRIPTION VARCHAR(500)
) COMMENT = 'B2B telecom product catalog - 10 enterprise connectivity products';

-- Dimension: Sales Reps (8 reps)
CREATE OR REPLACE TABLE DIM_SALES_REP (
    REP_ID INT PRIMARY KEY,
    REP_NAME VARCHAR(100),
    REGION VARCHAR(50),
    TEAM VARCHAR(50),
    HIRE_DATE DATE,
    QUOTA_EUR FLOAT
) COMMENT = 'B2B sales representatives covering Dutch enterprise accounts';

-- Dimension: Date (2 years)
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    FULL_DATE DATE,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    WEEK_OF_YEAR INT,
    DAY_OF_WEEK INT,
    IS_WEEKEND BOOLEAN,
    FISCAL_YEAR INT,
    FISCAL_QUARTER INT
) COMMENT = 'Date dimension covering 2 years for time-based analysis';

-- Fact: Sales Transactions
CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID INT AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID INT,
    PRODUCT_ID INT,
    REP_ID INT,
    DATE_ID INT,
    SALE_DATE DATE,
    QUANTITY INT,
    UNIT_PRICE_EUR FLOAT,
    DISCOUNT_PCT FLOAT,
    TOTAL_REVENUE_EUR FLOAT,
    DEAL_STATUS VARCHAR(20),
    CONTRACT_LENGTH_MONTHS INT,
    CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES DIM_COMPANY(COMPANY_ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_REP FOREIGN KEY (REP_ID) REFERENCES DIM_SALES_REP(REP_ID),
    CONSTRAINT FK_DATE FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
) COMMENT = 'Monthly B2B sales transactions - deals with Dutch enterprise accounts';

-- Company Intelligence (populated weekly by Brave Search)
CREATE OR REPLACE TABLE COMPANY_INTELLIGENCE (
    INTEL_ID INT AUTOINCREMENT PRIMARY KEY,
    COMPANY_ID INT,
    SEARCH_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SEARCH_QUERY VARCHAR(500),
    TITLE VARCHAR(500),
    SNIPPET VARCHAR(2000),
    URL VARCHAR(1000),
    SOURCE_TYPE VARCHAR(50),
    RELEVANCE_SCORE FLOAT,
    CONSTRAINT FK_INTEL_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES DIM_COMPANY(COMPANY_ID)
) COMMENT = 'Weekly Brave Search intelligence on enterprise accounts';
